### PR TITLE
reference static interface option; fix missing comma

### PR DESCRIPTION
**Pull request by flyinprogrammer**

### CODE REVIEW

**Comment by tgross** [comment]
@flyinprogrammer was this branched from an older base? TravisCI is giving us a linting error. Can you rebase if that's the case. Otherwise LGTM.

**Comment by flyinprogrammer** [comment]
> was this branched from an older base?
master this morning "This branch is 1 commit ahead of joyent:master."

**Comment by tgross** [comment]
Ugh, I see it now. Ok... we're installing `golint` in our builder via `go get` and [they just added this lint](https://github.com/golang/lint/commit/206c0f020eba0f7fbcfbc467a5eb808037df2ed6). As I've said before ["go get considered harmful"](http://0x74696d.com/posts/go-get-considered-harmful).

I've pulled your changes as-is into another branch so I can make that fix. I'm going to close this PR and then open another one so we can get the :+1: from Travis before merging. Thanks for your help @flyinprogrammer!

**Comment by tgross** [comment]
PR https://github.com/joyent/containerpilot/pull/241 opened. I've done this in such a way that @flyinprogrammer's commits are left intact so that he gets all the imaginary GitHub points. 😀

**Pull request closed without merging**
