### PR TITLE
upgrade to consul ~0.7.0

### PR DESCRIPTION
**Pull request by flyinprogrammer**
I'm running the tests locally right now, but let's see if this works in automation too?

### CODE REVIEW

**Comment by tgross** [comment]
LGTM. Can we rebase this on master so that we can run thru the integration tests again with the updated Consul container?

**Comment by flyinprogrammer** [comment]
yup - brb!

**Comment by flyinprogrammer** [comment]
interesting running this locally results in all kinds of intermittent failures, I'll have to dig into what these integration tests do/are and see if a pattern and solution emerges 😀

**Comment by flyinprogrammer** [comment]
I suspect this will pass; however, my `wait4consul` pattern is probably unacceptable. I can refactor this functionality into `test_probe`, and the already established pattern for accomplishing this goal.

**Comment by tgross** [comment]
> I suspect this will pass; however, my wait4consul pattern is probably unacceptable. I can refactor this functionality into test_probe, and use the established pattern for accomplishing this goal.

Is the problem just that we're using the `-dev` server now instead of doing a `bootstrap=true` / `bootstrap-expect=1`?

**Comment by flyinprogrammer** [comment]
no the problem is consul is just slower to boot up now, and we never had explicit waits in place.

**Comment by tgross** [comment]
Ok, LGTM.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.5.0

**Pull request merged**
