### PR TITLE
Prevent polling and coprocesses from being started multiple times

### PR DESCRIPTION
**Pull request by ddunkin**
Prevent polling and coprocesses from being started multiple times if a reload is triggered during preStart.

### CODE REVIEW

**Comment by tgross** [comment]
> Prevent polling and coprocesses from being started multiple times if a reload is triggered during preStart.

@ddunkin I just want to make sure I understand the problem as your describing it here:

The polling and coprocesses aren't started until after the `preStart` has exited (we block on the `preStart`). But if we receive a reload then the polling/coprocesses are started in `App.load`, which means when we exit `preStart` we load them again. This means we end up with 2 goroutines running for each pollable and two copies of each coprocess. Right?

If so, I think the approach you have here seems right. An alternate approach would be to start the signal handler after the `preStart` exits but then we'd lose the ability for the `preStart` to reconfigure ContainerPilot.

This fix needs extensive testing though. There are a *lot* of possible races and interleaving of events that we need to test to ensure we have no deadlocks and that we understand the secondary effects on heartbeat TTLs. Here's your happy path scenario where we start the co-work once and only once:

- App.Run()
  - start `preStart`
    - `preStart` fires SIGHUP
  - exit `preStart`
- signal handler->App.Reload()
    - App.Reload->a.stopCoworkAndDeregister() [obtain lock] [release lock]
    - App.Reload->a.load()
      - a.load()->a.startCowork() [obtain lock]
      - (all co-processes started)
- Service.SendHeartbeat()
- App.Run->a.startCowork() [block]
      - App.Reload->a.load()->a.startCowork exit [release lock]
- App.Run->a.startCowork() [obtains lock]
- App.Run->a.startCowork() exits w/ no-op


Here's a less happy path where we start and stop the co-work in a way that causes the application to become "unhealthy" after it's already been registered:

- App.Run()
  - start `preStart`
    - `preStart` fires SIGHUP
  - exit `preStart`
- App.Run->a.startCowork() [obtain lock]
      - (all co-processes started)
- Service.SendHeartbeat()
- signal handler->App.Reload()
    - App.Reload->a.stopCoworkAndDeregister() [blocks] [locks all signal handling!]
- App.Run->a.startCowork() exit [release lock]
- App.Reload->a.stopCoworkAndDeregister() [obtains lock]
  - (all co-processes stopped)
  - (service is deregistered)
  - App.Reload->a.load()
  - a.load()->a.startCowork() [obtain lock]
    - (all co-processes started)
  - App.Reload->a.load()->a.startCowork exit [release lock]
- Service.SendHeartbeat()

This looks to be *correct* behavior, to be sure. But if we're going to have this kind of behavior we need to test and document the heck out of it.

**Comment by ddunkin** [comment]
@tgross you understand correctly. I'll work on a test case today.

**Comment by ddunkin** [comment]
What is the problem in the second scenario laid out above? I don't see the difference between a SIGHUP from preStart being delayed and a SIGHUP from a health check or from an external sender (e.g. `docker kill --signal=HUP`).

As it is now (with or without this fix), there doesn't appear to be a way to force a reconfiguration from preStart to happen before anything else is started. If CP should support that behavior, it could reload based on a specific exit code from preStart.

**Comment by ddunkin** [comment]
Side note: I came across the duplicate health-check bug while updating https://github.com/Faithlife/redis-autopilot to the latest ContainerPilot. I want to run a Consul agent in container because we have problems with the Redis container registering with a different one of our three Consul server agents depending on the order of addresses returned by DNS. However I see now that coprocesses are not started until after preStart where I do the master/slave configuration of Redis, which requires Consul, so I don't think I'll be able to use preStart anyway.

**Comment by tgross** [comment]
> What is the problem in the second scenario laid out above?

It's not a problem, just a less obvious code path that causes the co-process to be restarted. I just want to make sure we're considering these cases so that (for example) the co-process restarts in that scenario work as we expect with their `restart` config.

> As it is now (with or without this fix), there doesn't appear to be a way to force a reconfiguration from preStart to happen before anything else is started.

Yeah that's kind of inherent to signal handling being async. Fair enough.

> However I see now that coprocesses are not started until after preStart where I do the master/slave configuration of Redis, which requires Consul, so I don't think I'll be able to use preStart anyway.

Yeah in cases like that you're going to want to put that into a periodic task or the health check, as we did in autopilotpattern/mysql. Unfortunately for every case like this, there's one where we want to configure to coprocess in `preStart` instead, so it's a matter of picking one behavior or the other.

**Comment by ddunkin** [comment]
> Unfortunately for every case like this, there's one where we want to configure to coprocess in preStart instead, so it's a matter of picking one behavior or the other.

`prePreStart`? ;)

There's a problem with putting the preStart checks in the health check. In the case of a redis master that has failed and is restarting, and another master has taken over while the original was down, I want to reconfigure the original to no longer be the master before it starts back up. There's no good place to hook in to make that check now.

**Comment by tgross** [comment]
> In the case of a redis master that has failed and is restarting, and another master has taken over while the original was down, I want to reconfigure the original to no longer be the master before it starts back up. 

We've done this sort of thing in autopilotpattern/mysql, using session keys in Consul to create a lock to coordinate the efforts of the instances. I'd recommend checking that out, although it's admittedly not trivial.

**Comment by tgross** [comment]
We still have no tests on this PR. I think the fix is important so I'll carry this PR once I have some time in the next week or two.

**Comment by ddunkin** [comment]
Sorry, I haven't had a chance to get back to this as it's no longer on my critical path. I may be able to get to it next week.

**Comment by tgross** [comment]
No worries @ddunkin I probably wouldn't be able to get to it until after then anyways.

**Comment by tgross** [comment]
We're going to keep fix this behavior in v3 but eliminate the coprocess behaviors outright. I'll try to carry this PR once we get to that point of the roadmap so we can keep @ddunkin's contributions if possible.

**Comment by tgross** [comment]
We can actually close this as the work is covered in #290

**Pull request closed without merging**
