### PR TITLE
Ability to configure telemetry service name

### PR DESCRIPTION
**Pull request by commarla**
This PR add the option to configure the telemetry service name.

### CODE REVIEW

**Comment by tgross** [comment]
Thanks for the PR @commarla! I'm not sure we want to do this, however.

Leaving out configurability of that service name was intentional in the original design (ref https://github.com/joyent/containerpilot/issues/27#issuecomment-198631596). I'm not sure about the reasoning _why_ though because unfortunately it wasn't written down. I'm pretty sure there was a sidebar discussion with @misterbisson but I don't recall the details... maybe he has some insight.

Design intent aside, before we could accept this PR we'd need to have a test demonstrating it works, that we check for invalid names, etc.

**Comment by commarla** [comment]
Hi @tgross,
Thanks for the quick reply.
I've just add the test.

**Comment by misterbisson** [comment]
@commarla it's very intentional that the ContainerPilot telemetry service name is not configurable. As @tgross pointed out, there were a lot of internal discussions on that point, as well as [some in the PR](https://github.com/joyent/containerpilot/pull/119#issuecomment-206955477).

The reasoning for this is our work to build a library of interoperable applications, as well as tools to manage them. Such a plan depends on well-known interfaces, and making the interface name configurable adds complexity well beyond the code changes here.

An example of the integration planned for this interface is in [RFD86](https://github.com/joyent/rfd/blob/master/rfd/0086/mariposa.md), which builds on [additional features proposed in the original ticket](https://github.com/joyent/containerpilot/issues/27#issuecomment-207462572) to report what's in the container, what it depends on, and what its status is.

With that roadmap and reasoning explained, I'd also like to better understand your motivation for wanting such a change?

**Comment by tgross** [comment]
Going to close this PR but I'm open to discussing it in a new issue if there are strong feelings about the design rationales laid out by @misterbisson in https://github.com/joyent/containerpilot/pull/292#issuecomment-291155741

**Pull request closed without merging**
