### PR TITLE
Remove etcd

### PR DESCRIPTION
**Pull request by tgross**
This PR removes support for etcd in ContainerPilot v3. Removing this early in the development cycle will reduce the overall testing and development load.

### CODE REVIEW

**Comment by misterbisson** [comment]
We'll also need to deprecate https://github.com/autopilotpattern/etcd

**Comment by tgross** [comment]
We're getting an odd seemingly-unrelated integration test error here that bears looking into:

```
2017/02/17 17:58:36 TEST: test_envvars
Creating testenvvars_consul_1
Timed out waiting for Consul.
2017/02/17 17:58:47 FAIL: test_envvars
```

**Comment by tgross** [comment]
I dug into the failed integration test and it appears to just be that the Consul target used by the env vars test sometimes takes longer than 10 seconds to self-elect.

I've increased the timeout and have been reliably able to get it to pass and we're now passing integration tests. In https://github.com/joyent/containerpilot/pull/282 I'll tweak the integration tests a bit so that we can share more of the test setup code and make the test targets a bit more clean / faster.

**Comment by tgross** [comment]
> We'll also need to deprecate https://github.com/autopilotpattern/etcd

Done in https://github.com/autopilotpattern/etcd/pull/3. I've also updated the docs to remove the relevant sections.

**Comment by misterbisson** [comment]
:pickles:

**Comment by tgross** [comment]
(Holding this up for an internal discussion. Don't merge please.)

**Pull request merged**
